### ISSUE TITLE
Support node.js 18

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/sheriff#7]
The bot runs on node.js 16.20.0 at the moment. If you're using node.js 18.x or 20.x, the bot fails to launch.

Support for node.js 18.x or newer is supported by discord.js, but not by the bot's code. Updating node.js allows updated npm to 10 or greater too.

**Comment by shivang-git** [comment]
hey @NotMyFault, I want to work on this issue... pls tell me do i need to create my discord token..

**Comment by NotMyFault** [comment]
> hey NotMyFault, I want to work on this issue... pls tell me do i need to create my discord token..

If you want to test the bot in production, yes.
